version: "3.5"
services:
  express-take-home:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=FIXME
      - LOG_LEVEL=debug
      - PORT=8080