version: "3.5"
services:
  express-take-home:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://postgres:password@host.docker.internal:5432/postgres
      - DISCOGS_API_TOKEN=${DISCOGS_API_TOKEN}
      - LOG_LEVEL=debug
      - PORT=8080
  postgres:
    image: postgres:13-alpine
    command: postgres -c 'max_connections=500'
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "/usr/local/bin/pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 120
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
